<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="OOPSDevelopmentTest" Id="{b8b13482-a341-41a8-a742-dcdb3e682f2a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM OOPSDevelopmentTest
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="OOPSDevelopmentTest">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>